apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: primmruuhub/back-end-wr:1.1.3
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata: 
  name: node-svc
spec:
  type: LoadBalancer
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000